# Generated by Django 5.2.14 on 2026-05-29 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='medio', max_length=20)),
                ('color', models.CharField(default='#FFA500', max_length=7)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías de Riesgo',
            },
        ),
        migrations.CreateModel(
            name='LineaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('METRO', 'Metro'), ('METROPLUS', 'Metroplús'), ('TRANVIA', 'Tranvía'), ('CABLE', 'Metrocable'), ('BUS', 'Bus')], max_length=20)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('color', models.CharField(default='#666666', max_length=7)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Líneas de Transporte',
            },
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relacion', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contactos de Emergencia',
            },
        ),
        migrations.CreateModel(
            name='EventoRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inundacion', 'Inundación'), ('deslizamiento', 'Deslizamiento'), ('incendio', 'Incendio'), ('sismo', 'Sismo'), ('accidente_vial', 'Accidente Vial'), ('explosion', 'Explosión'), ('fuga_gas', 'Fuga de Gas'), ('colapso', 'Colapso Estructural'), ('vendaval', 'Vendaval'), ('otro', 'Otro')], max_length=30)),
                ('nivel', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='medio', max_length=20)),
                ('fuente', models.CharField(choices=[('simur', 'SIMUR'), ('dagrd', 'DAGRD'), ('usuario', 'Reporte Usuario'), ('api_externa', 'API Externa')], default='usuario', max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('radio_impacto_metros', models.IntegerField(default=300)),
                ('activo', models.BooleanField(default=True)),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
                ('datos_raw', models.JSONField(blank=True, default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Eventos de Riesgo',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['latitud', 'longitud'], name='core_evento_latitud_4f687e_idx'), models.Index(fields=['activo', 'expira_en'], name='core_evento_activo_ce5e4e_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventoSOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('activo', models.BooleanField(default=True)),
                ('contactos_notificados', models.JSONField(blank=True, default=list)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_sos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Eventos SOS',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Favoritos',
            },
        ),
        migrations.CreateModel(
            name='HistorialViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_nombre', models.CharField(max_length=200)),
                ('destino_nombre', models.CharField(max_length=200)),
                ('origen_lat', models.FloatField(blank=True, null=True)),
                ('origen_lng', models.FloatField(blank=True, null=True)),
                ('destino_lat', models.FloatField(blank=True, null=True)),
                ('destino_lng', models.FloatField(blank=True, null=True)),
                ('distancia_km', models.FloatField(blank=True, null=True)),
                ('tiempo_min', models.IntegerField(blank=True, null=True)),
                ('costo_estimado', models.IntegerField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_viajes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Historial de Viajes',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('id_objeto', models.IntegerField(blank=True, null=True)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReporteIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('accidente', 'Accidente'), ('bloqueo', 'Bloqueo'), ('zona_peligrosa', 'Zona Peligrosa'), ('robo', 'Robo'), ('clima', 'Riesgo Climático'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('ubicacion_texto', models.CharField(blank=True, max_length=255)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='incidentes/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('oculto', 'Oculto')], default='pendiente', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('votos_positivos', models.IntegerField(default=0)),
                ('votos_negativos', models.IntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reportes de Incidentes',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ZonaRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('comuna', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_riesgo', models.CharField(choices=[('ACCIDENTE', 'Accidente'), ('VIOLENCIA', 'Violencia'), ('ROBO', 'Robo'), ('INUNDACION', 'Inundación'), ('DESLIZAMIENTO', 'Deslizamiento'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('nivel', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='MEDIO', max_length=20)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('radio_metros', models.IntegerField(default=500)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='core.categoriariesgo')),
            ],
            options={
                'verbose_name_plural': 'Zonas de Riesgo',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('nivel', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='MEDIO', max_length=20)),
                ('leida', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
                ('zona_riesgo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='core.zonariesgo')),
            ],
            options={
                'verbose_name_plural': 'Alertas',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('orden', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='core.lineatransporte')),
            ],
            options={
                'verbose_name_plural': 'Paradas',
                'ordering': ['linea', 'orden'],
                'unique_together': {('linea', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='VotoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.CharField(choices=[('positivo', 'Validar'), ('negativo', 'Desmentir')], max_length=20)),
                ('positivo', models.BooleanField(null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='core.reporteincidente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'reporte')},
            },
        ),
    ]
