# Generated by Django 4.2.30 on 2026-05-29 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('licencia', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Conductores',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('TRANSITO', 'En tránsito'), ('ENTREGADO', 'Entregado'), ('RETRASADO', 'Retrasado'), ('PERDIDO', 'Perdido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15)),
                ('origen', models.CharField(blank=True, max_length=200)),
                ('destino', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.conductor')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LineaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('METRO', 'Metro'), ('METROPLUS', 'Metroplús'), ('TRANVIA', 'Tranvía'), ('CABLE', 'Cable'), ('BUS', 'Bus')], max_length=15)),
                ('codigo', models.CharField(help_text='Código de línea (ej: L1, M1, T1, K1)', max_length=20, unique=True)),
                ('color', models.CharField(blank=True, help_text='Color hexadecimal', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Línea de transporte',
                'verbose_name_plural': 'Líneas de transporte',
            },
        ),
        migrations.CreateModel(
            name='ReporteIncidenteComunitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACCIDENTE', 'Accidente de tránsito'), ('BLOQUEO', 'Bloqueo de vía'), ('ZONA_PELIGROSA', 'Zona peligrosa'), ('ROBO', 'Robo / Hurto'), ('INUNDACION', 'Inundación'), ('DESLIZAMIENTO', 'Deslizamiento'), ('MANIFESTACION', 'Manifestación'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('ubicacion_texto', models.CharField(blank=True, max_length=300)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('foto_url', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('votos_positivos', models.IntegerField(default=0)),
                ('votos_negativos', models.IntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_comunitarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte comunitario',
                'verbose_name_plural': 'Reportes comunitarios',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('comuna_origen', models.CharField(blank=True, help_text='Comuna de origen en Medellín', max_length=100)),
                ('comuna_destino', models.CharField(blank=True, help_text='Comuna de destino en Medellín', max_length=100)),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tiempo_estimado_min', models.IntegerField()),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='MEDIO', max_length=10)),
                ('accesible', models.BooleanField(default=False, help_text='Ruta accesible para movilidad reducida')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Rutas',
            },
        ),
        migrations.CreateModel(
            name='ZonaRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('comuna', models.CharField(blank=True, help_text='Comuna de Medellín', max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo_riesgo', models.CharField(choices=[('VIOLENCIA', 'Violencia / Seguridad'), ('INUNDACION', 'Inundación'), ('DESLIZAMIENTO', 'Deslizamiento'), ('ACCIDENTE', 'Accidentalidad vial'), ('BLOQUEO', 'Bloqueo de vía'), ('OTRO', 'Otro')], max_length=20)),
                ('nivel', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='MEDIO', max_length=10)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radio_metros', models.IntegerField(default=500, help_text='Radio de la zona de riesgo en metros')),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Zonas de riesgo',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('tipo', models.CharField(choices=[('CAMION', 'Camión'), ('CAMIONETA', 'Camioneta'), ('TRACTO', 'Tractocamión'), ('FURGON', 'Furgón'), ('MOTO', 'Motocicleta')], max_length=20)),
                ('capacidad_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('MANTENIMIENTO', 'En mantenimiento'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('VEHICULO', 'Vehículo'), ('CARGA', 'Carga'), ('CONDUCTOR', 'Conductor'), ('RESP_CIVIL', 'Responsabilidad Civil')], max_length=20)),
                ('aseguradora', models.CharField(max_length=100)),
                ('cobertura', models.TextField()),
                ('prima', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.conductor')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.item')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehiculo')),
            ],
            options={
                'verbose_name_plural': 'Pólizas',
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('orden', models.IntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='core.lineatransporte')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ruta'),
        ),
        migrations.AddField(
            model_name='item',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehiculo'),
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACCIDENTE', 'Accidente'), ('ROBO', 'Robo'), ('AVERIA', 'Avería mecánica'), ('RETRASO', 'Retraso'), ('CLIMA', 'Clima adverso'), ('OTRO', 'Otro')], max_length=15)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('costo_danos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='core.item')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('frecuencia_min', models.IntegerField(help_text='Frecuencia en minutos')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.lineatransporte')),
            ],
            options={
                'verbose_name_plural': 'Horarios de transporte',
                'ordering': ['linea', 'dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_nombre', models.CharField(max_length=300)),
                ('destino_nombre', models.CharField(max_length=300)),
                ('origen_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('origen_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destino_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destino_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tiempo_min', models.IntegerField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_viajes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Historial de viajes',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=300)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Favoritos',
            },
        ),
        migrations.CreateModel(
            name='EventoSOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('activo', models.BooleanField(default=True)),
                ('contactos_notificados', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cerrado', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_sos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento SOS',
                'verbose_name_plural': 'Eventos SOS',
            },
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contactos de emergencia',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.item')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('nivel', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], max_length=10)),
                ('leida', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to=settings.AUTH_USER_MODEL)),
                ('zona_riesgo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zonariesgo')),
            ],
        ),
        migrations.CreateModel(
            name='VotoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positivo', models.BooleanField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='core.reporteincidentecomunitario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'reporte')},
            },
        ),
        migrations.CreateModel(
            name='MatrizRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.CharField(choices=[('CLIMA', 'Clima'), ('VIA', 'Estado de la vía'), ('SINIESTRO', 'Historial de siniestros'), ('TRAFICO', 'Tráfico'), ('GEO', 'Geografía')], max_length=15)),
                ('probabilidad', models.IntegerField(help_text='1-5')),
                ('impacto', models.IntegerField(help_text='1-5')),
                ('nivel', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], editable=False, max_length=10)),
                ('mitigacion', models.TextField(blank=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='core.ruta')),
            ],
            options={
                'verbose_name_plural': 'Matriz de riesgos',
                'unique_together': {('ruta', 'factor')},
            },
        ),
    ]
