# Generated by Django 5.2.14 on 2026-05-29 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('frecuencia_min', models.IntegerField()),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.lineatransporte')),
            ],
            options={
                'verbose_name_plural': 'Horarios de Transporte',
                'ordering': ['linea', 'dia_semana', 'hora_inicio'],
            },
        ),
    ]
