# Generated by Django 4.2.30 on 2026-06-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('avatar_url', models.URLField(blank=True)),
                ('calificacion', models.IntegerField(default=5)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonios',
                'ordering': ['-creado'],
            },
        ),
    ]
