# Generated by Django 5.0.14 on 2026-06-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineatransporte',
            name='ruta_geojson',
            field=models.TextField(blank=True, help_text='GeoJSON LineString de la ruta real (calles/vías que sigue)'),
        ),
    ]
