# Generated by Django 5.0.14 on 2026-06-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstacionPolicia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Estaciones de Policía',
                'indexes': [models.Index(fields=['latitud', 'longitud'], name='core_estaci_latitud_618327_idx')],
            },
        ),
        migrations.CreateModel(
            name='IncidenteHomicidio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('barrio', models.CharField(blank=True, max_length=200)),
                ('comuna', models.CharField(blank=True, max_length=100)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('fuente', models.CharField(blank=True, max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Incidentes de Homicidio',
                'indexes': [models.Index(fields=['latitud', 'longitud'], name='core_incide_latitud_722081_idx')],
            },
        ),
        migrations.CreateModel(
            name='IncidenteTransito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('gravedad', models.CharField(blank=True, max_length=50)),
                ('comuna', models.CharField(blank=True, max_length=100)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('fuente', models.CharField(blank=True, max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Incidentes de Tránsito',
                'indexes': [models.Index(fields=['latitud', 'longitud'], name='core_incide_latitud_fd2f77_idx')],
            },
        ),
    ]
