# Generated by Django 6.0.6 on 2026-06-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_estacionpolicia_incidentehomicidio_incidentetransito'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineatransporte',
            name='ruta_geojson',
            field=models.TextField(blank=True, null=True),
        ),
    ]
