# Generated by Django 5.0.14 on 2026-06-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lineatransporte_ruta_geojson'),
        ('core', '0006_lineatransporte_ruta_geojson'),
    ]

    operations = [
    ]
