# Generated by Django 5.0.14 on 2026-06-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20260606_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineatransporte',
            name='ruta_geojson',
            field=models.TextField(blank=True, null=True),
        ),
    ]
