# Generated by Django 5.0.14 on 2026-06-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_lineatransporte_ruta_geojson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteincidente',
            name='foto',
        ),
        migrations.AlterField(
            model_name='reporteincidente',
            name='latitud',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reporteincidente',
            name='longitud',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='zonariesgo',
            name='latitud',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='zonariesgo',
            name='longitud',
            field=models.FloatField(db_index=True),
        ),
    ]
