# Generated by Django 5.0.14 on 2026-06-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_reporteincidente_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(default='#00c853', max_length=7)),
                ('ruta_geojson', models.JSONField()),
                ('paradas', models.JSONField(default=list)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ruta de Transporte',
                'verbose_name_plural': 'Rutas de Transporte',
            },
        ),
    ]
