# Generated by Django 5.0.14 on 2026-06-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rutatransporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoriesgo',
            name='fuente',
            field=models.CharField(choices=[('simur', 'SIMUR'), ('dagrd', 'DAGRD'), ('usuario', 'Reporte Usuario'), ('api_externa', 'API Externa'), ('arcgis_dagrd', 'ArcGIS DAGRD'), ('arcgis_cierres', 'ArcGIS Cierres')], default='usuario', max_length=30),
        ),
        migrations.AlterField(
            model_name='eventoriesgo',
            name='tipo',
            field=models.CharField(choices=[('inundacion', 'Inundación'), ('deslizamiento', 'Deslizamiento'), ('incendio', 'Incendio'), ('sismo', 'Sismo'), ('accidente_vial', 'Accidente Vial'), ('explosion', 'Explosión'), ('fuga_gas', 'Fuga de Gas'), ('colapso', 'Colapso Estructural'), ('vendaval', 'Vendaval'), ('cierre_vial', 'Cierre Vial'), ('monitoreo', 'Punto de Monitoreo'), ('inspeccion', 'Inspección'), ('otro', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='zonariesgo',
            name='tipo_riesgo',
            field=models.CharField(choices=[('ACCIDENTE', 'Accidente'), ('VIOLENCIA', 'Violencia'), ('ROBO', 'Robo'), ('INUNDACION', 'Inundación'), ('DESLIZAMIENTO', 'Deslizamiento'), ('MONITOREO', 'Monitoreo'), ('INSPECCION', 'Inspección'), ('CIERRE', 'Cierre Vial'), ('OTRO', 'Otro')], default='OTRO', max_length=30),
        ),
    ]
